services:
  - type: web
    name: python-docs-rag-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: groq
      - key: FRONTEND_ORIGIN
        sync: false
